"""search_vector added

Revision ID: 614dea7afdd7
Revises: eac52b4348ce
Create Date: 2026-05-18 10:14:22.564583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '614dea7afdd7'
down_revision: Union[str, Sequence[str], None] = 'eac52b4348ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('search_vector', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'search_vector')
    # ### end Alembic commands ###
