"""initial jobs table

Revision ID: 843f5f8364a3
Revises: 
Create Date: 2026-05-09 16:29:42.602060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '843f5f8364a3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_job_id', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('application_url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('job_type', sa.Text(), nullable=True),
    sa.Column('work_mode', sa.Text(), nullable=True),
    sa.Column('remote', sa.Boolean(), nullable=True),
    sa.Column('org_name', sa.Text(), nullable=True),
    sa.Column('org_logo_url', sa.Text(), nullable=True),
    sa.Column('org_size', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.Text(), nullable=True),
    sa.Column('salary_period', sa.Text(), nullable=True),
    sa.Column('salary_display', sa.Text(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('stipend_min', sa.Integer(), nullable=True),
    sa.Column('stipend_max', sa.Integer(), nullable=True),
    sa.Column('stipend_display', sa.Text(), nullable=True),
    sa.Column('experience_min_years', sa.Float(), nullable=True),
    sa.Column('experience_max_years', sa.Float(), nullable=True),
    sa.Column('experience_label', sa.Text(), nullable=True),
    sa.Column('duration_display', sa.Text(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('skills', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('categories', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('eligibility', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('benefits', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('work_functions', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('posted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('scraped_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('dedupe_key', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('embedding_text', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('embedding_model', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    op.create_index('idx_jobs_categories', 'jobs', ['categories'], unique=False, postgresql_using='gin')
    op.create_index('idx_jobs_eligibility', 'jobs', ['eligibility'], unique=False, postgresql_using='gin')
    op.create_index('idx_jobs_embedding', 'jobs', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('idx_jobs_is_active', 'jobs', ['is_active'], unique=False)
    op.create_index('idx_jobs_job_type', 'jobs', ['job_type'], unique=False)
    op.create_index('idx_jobs_posted_at', 'jobs', ['posted_at'], unique=False)
    op.create_index('idx_jobs_remote', 'jobs', ['remote'], unique=False)
    op.create_index('idx_jobs_skills', 'jobs', ['skills'], unique=False, postgresql_using='gin')
    op.create_index('idx_jobs_source', 'jobs', ['source'], unique=False)
    op.create_index('idx_jobs_work_mode', 'jobs', ['work_mode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_jobs_work_mode', table_name='jobs')
    op.drop_index('idx_jobs_source', table_name='jobs')
    op.drop_index('idx_jobs_skills', table_name='jobs', postgresql_using='gin')
    op.drop_index('idx_jobs_remote', table_name='jobs')
    op.drop_index('idx_jobs_posted_at', table_name='jobs')
    op.drop_index('idx_jobs_job_type', table_name='jobs')
    op.drop_index('idx_jobs_is_active', table_name='jobs')
    op.drop_index('idx_jobs_embedding', table_name='jobs', postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('idx_jobs_eligibility', table_name='jobs', postgresql_using='gin')
    op.drop_index('idx_jobs_categories', table_name='jobs', postgresql_using='gin')
    op.drop_table('jobs')
    # ### end Alembic commands ###
