"""chat table updated

Revision ID: aec57494c43a
Revises: df2280789190
Create Date: 2026-05-30 22:28:01.959441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aec57494c43a'
down_revision: Union[str, Sequence[str], None] = 'df2280789190'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('retrieved_jobs', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('chats', sa.Column('last_retrieval_query', sa.Text(), nullable=True))
    op.add_column('chats', sa.Column('retrieval_updated_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'retrieval_updated_at')
    op.drop_column('chats', 'last_retrieval_query')
    op.drop_column('chats', 'retrieved_jobs')
    # ### end Alembic commands ###
