"""add cities column

Revision ID: c03af9179671
Revises: 8aaf45d0a9bb
Create Date: 2026-05-18 11:44:25.929798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c03af9179671'
down_revision: Union[str, Sequence[str], None] = '8aaf45d0a9bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('cities', sa.ARRAY(sa.Text()), nullable=True))
    op.drop_index(op.f('idx_jobs_search_vector'), table_name='jobs', postgresql_using='gin')
    op.create_index('idx_jobs_cities', 'jobs', ['cities'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_jobs_cities', table_name='jobs', postgresql_using='gin')
    op.create_index(op.f('idx_jobs_search_vector'), 'jobs', ['search_vector'], unique=False, postgresql_using='gin')
    op.drop_column('jobs', 'cities')
    # ### end Alembic commands ###
